language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - composer self-update
  - composer global require "hirak/prestissimo:^0.3"
install:
  - composer install --no-interaction
